// Generated by Wrangler on Mon Jul 15 2024 17:15:32 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
    LINE_CHANNEL_ACCESS_TOKEN: string,
    LINE_CHANNEL_SECRET: string,
    MY_USER_ID: string,
    NOTION_TOKEN: string,
    DATABASE_ID: string
}
