name = "diary-bot"
compatibility_date = "2024-07-15"
compatibility_flags = [ "nodejs_compat" ]


# [vars]
# MY_VAR = "my-variable"

[triggers]
crons = ["0 12 * * *","*/30 * * * *","0 21 * * *","0 */4 * * *","0 15 * * *"]

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"